---
# Installing promtail
- name: Install promtail if not installed
  block:
    - name: Create promtail user
      user:
        name: "{{ promtail_user }}"
        shell: /usr/bin/false
        create_home: false

    - name: Create promtail directory
      become: true
      file:
        path: /etc/promtail
        state: directory
        owner: "{{ promtail_user }}"
        group: "{{ promtail_user }}"

    - name: Download promtail
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
        dest: "{{ download_location }}"

    - name: Untar promtail
      unarchive:
        src: "{{ download_location }}/promtail-linux-amd64.zip"
        remote_src: true
        dest: "{{ download_location }}"

    - name: Copy promtail binary
      copy:
        src: "{{ download_location }}/promtail-linux-amd64"
        remote_src: true
        dest: /usr/local/bin/promtail
        mode: '0755'

    - name: Create config file
      copy:
        src: promtail.yml
        dest: /etc/promtail/promtail.yml
        owner: "{{ promtail_user }}"
        group: "{{ promtail_user }}"

    - name: Create systemd service for promtail
      copy:
        src: promtail.service
        dest: /etc/systemd/system/promtail.service

    # Post installation
    - name: Reload systemd config
      systemd:
        daemon_reload: true

    - name: Cleanup obsolete files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ download_location }}/promtail-linux-amd64.zip"
        - "{{ download_location }}/promtail-linux-amd64"

    # Edit firewall rules
    - name: Allow incoming traffic on port 9080
      firewalld:
        port: 9080/tcp
        permanent: true
        immediate: true
        state: enabled
      notify: Reload firewalld
      when: ansible_os_family == "RedHat" and 'firewalld' in ansible_facts.packages

    - name: Promtail enable + restart
      command: /bin/true
      notify: Restart Promtail
  when: promtail_install and ansible_facts.services["promtail.service"] is not defined
