---
# Installing promtail
- name: Create promtail user
  user:
    name: "{{ promtail_user }}"
    shell: /usr/bin/false
    create_home: false

- name: Create promtail directory
  file:
    path: /etc/promtail
    state: directory
    owner: "{{ promtail_user }}"
    group: "{{ promtail_user }}"

- name: Get promtail version
  shell: "promtail --version | grep 'promtail, version' | cut -d ' ' -f 3"
  register: promtail_version_current
  changed_when: false
  when: ansible_facts.services["promtail.service"] is defined

- name: Install/update promtail binary
  block:
    - name: Download promtail
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ promtail_architecture }}.zip"
        dest: /tmp

    - name: Unzip promtail
      unarchive:
        src: "/tmp/promtail-linux-{{ promtail_architecture }}.zip"
        remote_src: true
        dest: /tmp

    - name: Copy promtail binary
      copy:
        src: "/tmp/promtail-linux-{{ promtail_architecture }}"
        remote_src: true
        dest: /usr/local/bin/promtail
        mode: '0755'
      notify: Restart Promtail
  when: promtail_version_current is not defined or promtail_version_current.stdout | default('') != promtail_version

- name: Create config file
  template:
    src: promtail.yml.j2
    dest: /etc/promtail/promtail.yml
    owner: "{{ promtail_user }}"
    group: "{{ promtail_user }}"
  notify: Restart Promtail

- name: Create systemd service for promtail
  copy:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Promtail
